local Loc = LibStub("AceLocale-3.0"):NewLocale("DetailsDmgRank", "ptBR") 

if (not Loc) then
	return 
end 

--> Labels:
Loc ["STRING_PLUGIN_NAME"] = "Dano, o Jogo!"
Loc ["STRING_CURRENTRANK"] = "Seu rank atual:"
Loc ["STRING_LASTTRIES"] = "Ultimas tentativas:"
Loc ["STRING_ANNOUNCE"] = "anunciar"
Loc ["STRING_ANNOUNCE_STRING"] = "alcancou o nivel"
Loc ["STRING_ANNOUNCE_ON"] = "no"
Loc ["STRING_LASTRANKS"] = "Ultimos ranks:"
Loc ["STRING_DAMAGEIN"] = "de dano em"
Loc ["STRING_SECONDS"] = "segundos"
Loc ["STRING_RANK"] = "rank"
Loc ["STRING_CANCELLED"] = "Esta tentativa foi cancelada."
Loc ["STRING_CANCELLED_NOT_COMBAT"] = "Esta tentativa foi cancelada: você não esta mais em combate."
Loc ["STRING_CANCELLED_IN_GROUP"] = "Esta tentativa foi cancelada: você está em grupo."
Loc ["STRING_CANCELLED_AURA"] = "Esta tentativa foi cancelada: buff proibido: "
Loc ["STRING_HELP"] = "Rank de Dano eh uma ferramenta interativa cujo o objetivo eh conseguir alcancar a margem de dano pedida dentro do tempo estabelecido. Cada vez que voce alcanca-lo, seu nivel aumenta e o desafio torna-se maior."

--> Challenge Names:
Loc ["CHALLENGENAME_1"] = "Pronto Para Raidar"
Loc ["CHALLENGENAME_2"] = "Pratique, pratique, pratique"
Loc ["CHALLENGENAME_3"] = "Continue a treinar"
Loc ["CHALLENGENAME_4"] = "Um Pouco Mais de Tempo"
Loc ["CHALLENGENAME_5"] = "Tornando-se um Cavalheiro"
Loc ["CHALLENGENAME_6"] = "2 minutos"
Loc ["CHALLENGENAME_7"] = "Maos de Mithril"
Loc ["CHALLENGENAME_8"] = "A Alta Cavalaria"
Loc ["CHALLENGENAME_9"] = "Sim Senhor!"
Loc ["CHALLENGENAME_10"] = "Continencia"
Loc ["CHALLENGENAME_11"] = "Na Explosão Nós Confiamos"
Loc ["CHALLENGENAME_12"] = "Me Veja Explodir"
Loc ["CHALLENGENAME_13"] = "T.N.T"
Loc ["CHALLENGENAME_14"] = "Tempo é Dano Meu Amigo"
Loc ["CHALLENGENAME_15"] = "Apenas um Pouco de Paciência"
Loc ["CHALLENGENAME_16"] = "Meu Dano Calcula-se Em Milésimos"
Loc ["CHALLENGENAME_17"] = "Prova Do Equipamento"
Loc ["CHALLENGENAME_18"] = "Apenas Faça..."
Loc ["CHALLENGENAME_19"] = "Eu Lembro de Você... no Detalhes!"

--> Rank Names:
Loc ["RANKNAME_1"] = "Fazendeiro"
Loc ["RANKNAME_2"] = "Soldado"
Loc ["RANKNAME_3"] = "Cabo"
Loc ["RANKNAME_4"] = "Sargento de Ouro"
Loc ["RANKNAME_5"] = "Sargento Estrela"
Loc ["RANKNAME_6"] = "Cavaleiro de Ferro"
Loc ["RANKNAME_7"] = "Cavaleiro de Aço"
Loc ["RANKNAME_8"] = "Cavaleiro de Mithril"
Loc ["RANKNAME_9"] = "Cavaleiro de Thorium"
Loc ["RANKNAME_10"] = "Tenente de Prata"
Loc ["RANKNAME_11"] = "Tenente de Ouro"
Loc ["RANKNAME_12"] = "Guardião de Pedra"
Loc ["RANKNAME_13"] = "Guardião Vil"
Loc ["RANKNAME_14"] = "Guardião Titânico"
Loc ["RANKNAME_15"] = "Centurião de Bronze"
Loc ["RANKNAME_16"] = "Centurião de Prata"
Loc ["RANKNAME_17"] = "Centurião das Chamas"
Loc ["RANKNAME_18"] = "Vencedor Menor"
Loc ["RANKNAME_19"] = "Vencedor"
Loc ["RANKNAME_20"] = "Vencedor Maior"