local Loc = LibStub("AceLocale-3.0"):NewLocale("Details_EncounterDetails", "zhCN") 

if (not Loc) then
	return 
end 

Loc ["STRING_PLUGIN_NAME"] = "战斗细节"
Loc ["STRING_WINDOW_TITLE"] = "Details!战斗信息"
Loc ["STRING_TOTAL_DAMAGE"] = "总伤害"
Loc ["STRING_TOTAL_HEAL"] = "总治疗"
Loc ["STRING_SHOW_ALL_DATA"] = "显示整体数据"
Loc ["STRING_SHOW_PHASE_DATA"] = "显示此片段的详细信息"
Loc ["STRING_NOT IMPLEMENTED"] = "尚未实现"
Loc ["STRING_DIED"] = "死亡"
Loc ["STRING_MELEE_DAMAGE"] = "肉搏伤害"
Loc ["STRING_DAMAGE_TAKEN_REPORT"] = "受到的伤害"
Loc ["STRING_ABILITY_DAMAGE"] = "技能伤害"
Loc ["STRING_DAMAGE_TAKEN"] = "承受伤害"
Loc ["STRING_TOOK_DAMAGE_FROM"] = "受到伤害"
Loc ["STRING_INTERRUPT_BY"] = "打断"
Loc ["STRING_DISPELLED_BY"] = "驱散"
Loc ["STRING_DEAD_LOG"] = "最后几秒"
Loc ["STRING_CURRENT"] = "当前"
Loc ["STRING_TRY"] = "战斗"
Loc ["STRING_DAMAGE_AT"] = "承受伤害"
Loc ["STRING_INFLICTED_BY"] = "造成的伤害"
Loc ["STRING_INFLICTED"] = "造成的伤害"
Loc ["STRING_ADDS"] = "ADDS"
Loc ["STRING_INTERRUPTS"] = "打断"
Loc ["STRING_INTERRUPTS_OF"] = "打断"
Loc ["STRING_DISPELLS_OF"] = "驱散"
Loc ["STRING_DISPELLS"] = "驱散"
Loc ["STRING_DEATH_LOG"] = "死亡日志"
Loc ["STRING_FIGHT_SUMMARY"] = "战斗总结"
Loc ["STRING_FIGHT_GRAPHIC"] = "战斗图表和阶段"
Loc ["STRING_FIGHT_EMOTES"] = "战斗台词"
Loc ["STRING_FIGHT_SPELLS"] = "战斗法术和光环"
Loc ["STRING_TOOLTIP"] = "显示战斗细节窗口"
Loc ["STRING_LAST_COOLDOWN"] = "上次使用的CD"
Loc ["STRING_NOLAST_COOLDOWN"] = "未使用CD"

Loc ["STRING_BOSS_NOT_REGISTRED"] = "此次战斗没有收录在Details!\n确保在角色选择屏幕上通过插件控制面板启用此团本."

Loc ["STRING_HOLDSHIFT"] = "SHIFT For Spell Description"

Loc ["STRING_ADDS_HELP"] = "鼠标悬停在|cFF00FF00箭头向上|r\n为dmg收到，|cFFFF0000箭头\n|cFFFF0000向下|r为dmg处理。 |cFFFFFF00单击\n|cFFFFFF00箭头|r：报告工具提示上显示的数据."
Loc ["STRING_INTERRIPT_HELP"] = " |cFFFFFF00点击|r一个计量条：\n打开报告窗口。\n在右边，我们根据\n总的时间来计算\n打断的次数."
Loc ["STRING_DISPELL_HELP"] = " \n|cFFFFFF00点击|r一个计量条:\n打开报告窗口."
Loc ["STRING_DEATHS_HELP"] = " \n|cFFFFFF00点击|r一个计量条:\n打开报告窗口."

Loc ["STRING_HEAL"] = "治疗"
Loc ["STRING_LOWDPS"] = "最低伤害"
Loc ["STRING_LOWHEAL"] = "最低治疗"
Loc ["STRING_VOIDZONE"] = "真空区"
Loc ["STRING_DISPELL"] = "驱散"
Loc ["STRING_INTERRUPT"] = "打断"
Loc ["STRING_POSITIONING"] = "定位"
Loc ["STRING_RUNAWAY"] = "脱控"
Loc ["STRING_TANKSWITCH"] = "坦克开怪"
Loc ["STRING_MECHANIC"] = "技能命中效果"
Loc ["STRING_CROWDCONTROL"] = "群体控制"
Loc ["STRING_TANKCOOLDOWN"] = "坦克CD"
Loc ["STRING_KILLADD"] = "击杀add"
Loc ["STRING_SPREADOUT"] = "扩散"
Loc ["STRING_STOPCAST"] = "停止施法"
Loc ["STRING_FACING"] = "面对"
Loc ["STRING_STACK"] = "堆"
